server {
    listen       8080;
    server_name  localhost;

    # Always use UTF-8
    charset utf-8;
    charset_types *;

    # Add headers to disable caching
    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    add_header Pragma "no-cache";
    add_header Expires "0";

    # Add security headers
    add_header Content-Security-Policy "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; form-action 'self'; frame-ancestors 'none';";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";

    # Directly serve files under the /static/ path
    location /static/font {
        root /usr/share/nginx/html;
        charset "";
    }
    location /static/ {
        root /usr/share/nginx/html;
    }
    location /favicon.ico {
        root /usr/share/nginx/html/static/img;
        charset "";
    }

    # Redirect all other requests to the root index.html
    location / {
        root /usr/share/nginx/html;
        index    index.html;
        try_files $uri /index.html;
    }

    error_page  404              /404.html;
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
