# Static configuration
# accessLog: {}
log:
  # level: DEBUG
  level: FATAL
api:
  insecure: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
providers:
  file:
    filename: /traefik-config.yml
    watch: false
  docker:
    exposedByDefault: false

# Dynamic configuration
tls:
  options:
    default:
      minVersion: VersionTLS13
  stores:
    default:
      defaultCertificate:
        certFile: /cert/cert.crt
        keyFile: /cert/cert.key
